// <auto-generated />
namespace MissionPlanningWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EquipmentName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EquipmentName));
        
        string IMigrationMetadata.Id
        {
            get { return "201403261722442_EquipmentName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
